# Generated by Django 3.1.4 on 2020-12-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201230_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='temp',
            field=models.IntegerField(),
        ),
    ]
