# Generated by Django 3.1.4 on 2020-12-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201230_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='temp',
        ),
    ]
