# Generated by Django 3.1.4 on 2020-12-31 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201230_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='place',
        ),
    ]
